### PR TITLE
Use Security Manager instead of an Exception to get the caller

### LINKED ISSUE #2: Performance: Choose the quickest available way to get the caller
Currently the implementation uses the StackTrace of a Throwable to get the Caller class, and then uses Strings to compare the Class names. https://stackoverflow.com/a/2924426 has examples on how to use the Reflection class/Security manager to get the caller class way faster. Best-case gatekeeper should check for the fastest available method(since the Reflection way is sadly deprecated without replacement) that the runtime JVM has to offer. 
Doing a quick test with optimized class lookups(only getting the target class when the caller was not allowed), comparing classes instead of class-names and the Reflection way of getting the caller class speed up checks from ~400k checks/second to ~9million checks/second.

### PR DESCRIPTION
**Pull request by tr7zw**
Pull Request to #2.
Uses an internal security manager to get the calling class, and only in case of a mismatch uses the StackTrace to get the exact method. Currently is failing one test because technically the test uses the wrong message: The test expects that gatekeeper finds ``org.assertj.core.api.ThrowableAssert``, but the security manager finds ``nl.altindag.gatekeeper.GatekeeperShould$$Lambda$...`` which is technically more correct since the ThrowableAssert class calls the anonymous inner lambda which then calls the method. Here the real question is rather an inner class should be treated as its outer class since you can't whitelist the anonymous classes.

In regards to performance, doing a really quick test it jumped from ~550k requests to ~2.1million requests in a second without any code warmup or perfect micro benchmarking.

### CODE REVIEW

File: src/main/java/nl/altindag/gatekeeper/Gatekeeper.java [hunk 1]
```diff
@@ -34,29 +34,37 @@ public static void ensureCallerIsAnyOf(Class... allowedCallerClasses) {
...
-        StackTraceElement[] stackTrace = new Exception().getStackTrace();
-        StackTraceElement caller = stackTrace[2];
-        StackTraceElement target = stackTrace[1];
-
-        boolean isCallerAllowedToCallTarget = isCallerAllowedToCallTarget(allowedCallerClasses, caller.getClassName());
+        Class<?> caller = internalSecurityManager.getCallerClassName(3);
+        boolean isCallerAllowedToCallTarget = isCallerAllowedToCallTarget(allowedCallerClasses, caller);
 
         if (!isCallerAllowedToCallTarget) {
+            StackTraceElement[] stackTrace = new Exception().getStackTrace();
```
Comment (Hakky54) [inline src/main/java/nl/altindag/gatekeeper/Gatekeeper.java:41]: It would be nice if we can inline this one. We don't need the stacktrace, but just only the target. What do you think?.

```
StackTraceElement target = new Exception().getStackTrace()[1];

File: src/main/java/nl/altindag/gatekeeper/Gatekeeper.java [hunk 2]
```diff
@@ -34,29 +34,37 @@ public static void ensureCallerIsAnyOf(Class... allowedCallerClasses) {
...
         return false;
     }
+    
+    private static class InternalSecurityManager extends SecurityManager {
+        public Class<?> getCallerClassName(int callStackDepth) {
+            return getClassContext()[callStackDepth];
+        }
+    }
+
+    private final static InternalSecurityManager internalSecurityManager =
```
Comment (Hakky54) [inline src/main/java/nl/altindag/gatekeeper/Gatekeeper.java:67]: Is it possible to make the left hand side of the type SecurityManager instead of the implementation? And maybe renaming it into SECURITY_MANAGER_INSTANCE as it the common naming convention for constant variables.

**Comment by Hakky54** [comment]
Hey @tr7zw thank you for this awesome PR. I dropped a couple of small remarks. I will check out the unit test, especially the failing one
